### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Natsumi-sama** [zkxs/vrcx-optimal-time#1]
I've never used rust before but the hardest part I found about using this tool was figuring out how the heck to import into google sheets lol I got there in the end by pasting into Excel then export as csv for import into google sheets.

Ran into a small bug but it wasn't much of an issue to add a check for. `thread 'main' panicked at 'index out of bounds: the len is 1246 but the index is 1246', src\main.rs:193:18`

> because VRCX actually stores timestamps correctly (thanks VRCX devs).

Don't worry this pains me more than anyone my largest regret when switching to sqlite storage was not switching everything to UTC it unfortunately never occurred to me at the time.

But here's my end result and it looks about right, 3am for me is 11pm JST/KST so I can see when these friend groups jump online then slowly trail off.
![Screenshot 2022-11-03 131637](https://user-images.githubusercontent.com/11171153/199625889-dd0a8bf1-638d-4387-a9fd-e0224f1da068.png)

Awesome tool! I'm sorry you had to deal with this sorry state of a database.

**Comment by zkxs** [comment]
> I've never used rust before but the hardest part I found about using this tool was figuring out how the heck to import into google sheets

Well, welcome to Rust. It's a hell of a language.

I personally just paste the program output into the first cell in Google Sheets, and that works. Google Sheets *should* just be able to take the output directly. If your terminal is replacing my tabs with spaces that might be causing issues... you could run `vrcx-optimal-time.exe > output.txt` to work around that if it's happening, though. 

> Don't worry this pains me more than anyone my largest regret when switching to sqlite storage was not switching everything to UTC it unfortunately never occurred to me at the time.

lol I did not expect the VRCX devs to actually see my "thanks VRCX devs". I feel like senpai has noticed me.

I'm not sure what you're saying here, though? All the timestamps in my DB look like `2020-09-14T12:18:55.213Z`, which sure looks like UTC to me? Or did I get on the VRCX bandwagon late enough that I missed an era of lackluster timestamps?

> `thread 'main' panicked at 'index out of bounds: the len is 1246 but the index is 1246', src\main.rs:193:18`

That OOB is interesting... I thought my indexing math was correct. What version are you running? It looks like you might be on the current master (fc438f39) to me?

> Awesome tool! I'm sorry you had to deal with this sorry state of a database.

Well, I'm glad people are liking it. I didn't actually expect anyone to find it, so this is a pleasant surprise.

Your database format seems fine to me. I'm mainly just happy VRCX uses sqlite for all these logs and not some massive evil json file.

**Comment by zkxs** [comment]
> The datetime format and timezone being local has always been this way, I thought you were joking because it's in UTC format but not UTC timezone so there are indeed all sorts of "weird daylight-savings-time edge-cases".

Oh god oh fuck. BUT THE Z MEANS UTC. I can't believe you've done this. My code is assuming that the UTC timezoned ISO-8601 dates aren't, you know, lying, so in adjusting "UTC" back into local I'm sure I'm just completely botching the offset. Ugh.

I'll try and comprehend why my array indexing is failing and fix it, I guess. I'm not sure what I can do about VRCX lying about timezone, though.

**Comment by zkxs** [comment]
In [app.js#L7177](https://github.com/pypy-vrc/VRCX/blob/07b2ecefa90ed16f49a414a3ef257c474e051ef6/html/src/app.js#L7177) setting `created_at` to `new Date().toJSON()` looks correct to me though? I'm no javascript expert, but that looks like it is recording the time correctly and not applying a fake timezone.

**Comment by Natsumi-sama** [comment]
You are correct that is UTC, sorry for the confusion I guess my memory is failing me, well daylight savings does cause some weird bugs with VRCX not sure how but oh well.
