### ISSUE TITLE
VRCX Optimal Time Viewer

### ISSUE THREAD

**Issue by RubenPX** [zkxs/vrcx-optimal-time#18]
yesterday i made a simple project that show graph of VRCX Optimal Time. This was a personal project but i decide to share with you, maybe it can help you to visualize data

https://github.com/PX-Byte/vrcx-optimal-time-viewer

![image](https://user-images.githubusercontent.com/23123160/220924248-6e6804cd-1de1-419a-ab28-9300557a8f98.png)

**Comment by zkxs** [comment]
This is really neat! Much less hassle than dealing with Excel or Google Sheets. Do you mind if I link to https://px-byte.github.io/vrcx-optimal-time-viewer/ from my readme?

**Comment by RubenPX** [comment]
Of course you can, feel free to link in readme. Additionally, if you have ideas or if you find any issue, feel free to tell me.
