### ISSUE TITLE
Can we get an example of how to paste this data into Google Sheets and create a chart?

### ISSUE THREAD

**Issue by Toxic-Cookie** [zkxs/vrcx-optimal-time#6]
I have literally no idea how to copy this data and properly paste it into google sheets and make a chart out of it. I kinda somehow got the split text to columns thing to work after maybe copying all the text straight off a cmd window but not really? The usage instructions for actually making use of the data is pretty vague in it's description. Also it would be nice if it just cleanly outputted this data to a text file.

**Comment by zkxs** [comment]
I've cleaned up my Google Sheet to the point where I can share it as an example: [here it is](https://docs.google.com/spreadsheets/d/11kGoZD9BTLpWUGHI9X7rCUGkWk6E5rVGCPmMivXf5_U/edit?usp=sharing).

At some point I might sit down and play with in-rust chart rendering, which would automate this whole process.

**Comment by zkxs** [comment]
I've added a bit more detail to the readme in 89efde07, which I believe addresses this issue.
